<a href="https://colab.research.google.com/github/minhaz1172/Deep-Learning/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#we can create  ensors using TensorFlow’s tf.Tensor() or its various helper functions, such as tf.constant(), tf.Variable(), or tf.zeros():
import tensorflow as tf

# Create a 0D tensor
scalar_tensor = tf.constant(42)
print("0D tensor:",scalar_tensor)

#vector(1D tensor)
vector_tensor=tf.constant([1, 2, 3])
print("1D tensor:",vector_tensor)
#matrix(2d tensor)
matrix=tf.constant([[1,3,5,7],[2,5,9,8]])
print("2D tensor:",matrix)

#3d tensor
tensor_3d=tf.constant([[[1,2],[3,5]],[[4,5],[6,7]]])
print("3D tensor:",tensor_3d)

#zeros tensor
zeros=tf.zeros([2,2])# 2 by 2 matrix of zeros
print("Zeros tensor:",zeros)
#tensors of ones
ones=tf.ones([3,3])# 3 by 3 matrix of ones
print("Ones tensor:",ones)


0D tensor: tf.Tensor(42, shape=(), dtype=int32)
1D tensor: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
2D tensor: tf.Tensor(
[[1 3 5 7]
 [2 5 9 8]], shape=(2, 4), dtype=int32)
3D tensor: tf.Tensor(
[[[1 2]
  [3 5]]

 [[4 5]
  [6 7]]], shape=(2, 2, 2), dtype=int32)
Zeros tensor: tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
Ones tensor: tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
